spring:
  application:
    name: BulkEmailChecker
  docker:
    compose:
      enabled: false
  # Enable response compression
  server:
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/plain
      min-response-size: 1024
  # Set reasonable connection timeouts
  mvc:
    async:
      request-timeout: 60s
  # Disable default security
  security:
    user:
      name: disabled
      password: disabled

# Server configuration
server:
  port: 8085
  # Enable HTTP/2
  http2:
    enabled: true
  # Optimize connection handling
  tomcat:
    threads:
      max: 40
      min-spare: 10
    max-connections: 400
    accept-count: 200
    connection-timeout: 3s
    max-keep-alive-requests: 200
    keep-alive-timeout: 60s
  # Enable response compression
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

# Logging configuration
logging:
  level:
    root: INFO
    com.mikov.bulkemailchecker: INFO
    com.mikov.bulkemailchecker.services: DEBUG
    com.mikov.bulkemailchecker.validation: INFO
    com.mikov.bulkemailchecker.controller: INFO
    org.springframework.web: WARN
    org.springframework.security: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# JVM Options to add when deploying:
# -Xms512m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication